services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Maispace\MaiEvents\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'

  Maispace\MaiEvents\EventProvider\EventProviderInterface:
    tags:
      - name: maispace.events.event_provider

  Maispace\MaiEvents\EventProvider\TxEventProvider:
    tags:
      - name: maispace.events.event_provider

  Maispace\MaiEvents\DataProcessor\EventsDataProcessor:
    arguments:
      $eventProviders: !tagged_iterator maispace.events.event_provider

  Maispace\MaiEvents\Controller\EventsController:
    arguments:
      $eventProviders: !tagged_iterator maispace.events.event_provider
    public: true

  Maispace\MaiEvents\Controller\RegistrationController:
    public: true

  Maispace\MaiEvents\Controller\Backend\RegistrationBackendController:
    public: true

  Maispace\MaiEvents\Indexer\EventIndexer:
    tags:
      - name: 'maispace.search.indexer'
      - name: 'maispace.search.result_formatter'
